-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Enable pgvector extension for RAG
create extension if not exists vector;

-- Users Profile Table (Extends Supabase Auth)
create table public.profiles (
  id uuid references auth.users not null primary key,
  email text not null,
  full_name text,
  is_pro boolean default false,
  stripe_customer_id text,
  subscription_status text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS on Profiles
alter table public.profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- Companies Table
create table public.companies (
  id bigint generated by default as identity primary key,
  ticker text not null unique,
  cik text not null unique,
  name text not null,
  exchange text,
  industry text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.companies enable row level security;
create policy "Companies are viewable by everyone." on companies for select using (true);

-- Filings Table
create table public.filings (
  id bigint generated by default as identity primary key,
  company_id bigint references public.companies(id) not null,
  accession_number text not null unique,
  filing_type text not null, -- '10-K', '10-Q'
  filing_date date not null,
  period_end_date date,
  sec_url text not null,
  report_url text,
  is_processed boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.filings enable row level security;
create policy "Filings are viewable by everyone." on filings for select using (true);

-- Filing Chunks (For RAG)
create table public.filing_chunks (
  id bigint generated by default as identity primary key,
  filing_id bigint references public.filings(id) on delete cascade not null,
  chunk_index integer not null,
  content text not null,
  section_name text, -- 'risk_factors', 'mda', etc.
  embedding vector(1536), -- 1536 dimensions for OpenAI embeddings
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.filing_chunks enable row level security;
create policy "Chunks are viewable by everyone." on filing_chunks for select using (true);

-- Index for vector similarity search
create index on public.filing_chunks using ivfflat (embedding vector_cosine_ops)
with (lists = 100);

-- Watchlist Table
create table public.watchlists (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  company_id bigint references public.companies(id) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, company_id)
);

alter table public.watchlists enable row level security;

create policy "Users can view their own watchlist."
  on watchlists for select
  using ( auth.uid() = user_id );

create policy "Users can insert into their own watchlist."
  on watchlists for insert
  with check ( auth.uid() = user_id );

create policy "Users can delete from their own watchlist."
  on watchlists for delete
  using ( auth.uid() = user_id );

-- Function to handle new user creation
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, email, full_name)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name');
  return new;
end;
$$ language plpgsql security definer;

-- Trigger for new user creation
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Vector Search Function
create or replace function match_filing_chunks (
  query_embedding vector(1536),
  match_threshold float,
  match_count int,
  filter_filing_id bigint
)
returns table (
  id bigint,
  content text,
  chunk_index int,
  similarity float
)
language plpgsql
as $$
begin
  return query
  select
    filing_chunks.id,
    filing_chunks.content,
    filing_chunks.chunk_index,
    1 - (filing_chunks.embedding <=> query_embedding) as similarity
  from filing_chunks
  where filing_chunks.filing_id = filter_filing_id
  and 1 - (filing_chunks.embedding <=> query_embedding) > match_threshold
  order by filing_chunks.embedding <=> query_embedding
  limit match_count;
end;
$$;
