import asyncio
import csv
import io
import re
from datetime import datetime
from html import escape

from app.models import Summary, Filing
from app.services.summary_sections import Block, Section, render_sections

class ExportService:
    def __init__(self):
        pass

    def generate_pdf_html(self, summary: Summary, filing: Filing) -> str:
        """Generate HTML for PDF export"""
        raw_summary = summary.raw_summary or {}

        html = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="UTF-8">
            <style>
                body {{
                    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
                    line-height: 1.6;
                    color: #1f2937;
                    max-width: 800px;
                    margin: 0 auto;
                    padding: 40px 20px;
                }}
                h1 {{
                    color: #111827;
                    border-bottom: 3px solid #3b82f6;
                    padding-bottom: 10px;
                    margin-bottom: 30px;
                }}
                h2 {{
                    color: #1f2937;
                    margin-top: 30px;
                    margin-bottom: 15px;
                    border-bottom: 1px solid #e5e7eb;
                    padding-bottom: 5px;
                }}
                h3 {{
                    color: #374151;
                    margin-top: 20px;
                    margin-bottom: 10px;
                }}
                table {{
                    width: 100%;
                    border-collapse: collapse;
                    margin: 20px 0;
                }}
                th, td {{
                    border: 1px solid #e5e7eb;
                    padding: 12px;
                    text-align: left;
                }}
                th {{
                    background-color: #f3f4f6;
                    font-weight: 600;
                }}
                .header {{
                    margin-bottom: 30px;
                    padding-bottom: 20px;
                    border-bottom: 2px solid #e5e7eb;
                }}
                .metadata {{
                    color: #6b7280;
                    font-size: 0.9em;
                    margin-bottom: 10px;
                }}
                .footer {{
                    margin-top: 40px;
                    padding-top: 20px;
                    border-top: 1px solid #e5e7eb;
                    color: #6b7280;
                    font-size: 0.85em;
                    text-align: center;
                }}
                ul {{
                    margin: 10px 0;
                    padding-left: 20px;
                }}
                li {{
                    margin: 5px 0;
                }}
                blockquote {{
                    margin: 10px 0;
                    padding-left: 15px;
                    border-left: 3px solid #e5e7eb;
                    color: #374151;
                    font-style: italic;
                }}
            </style>
        </head>
        <body>
            <div class="header">
                <h1>{escape(filing.company.name or '')} - {escape(filing.filing_type or '')} Summary</h1>
                <div class="metadata">
                    <p><strong>Filing Date:</strong> {filing.filing_date.strftime('%B %d, %Y') if filing.filing_date else 'N/A'}</p>
                    <p><strong>Period End:</strong> {filing.period_end_date.strftime('%B %d, %Y') if filing.period_end_date else 'N/A'}</p>
                    <p><strong>Generated:</strong> {datetime.now().strftime('%B %d, %Y at %I:%M %p')}</p>
                    <p><strong>Source:</strong> SEC EDGAR - {escape(filing.sec_url or '')}</p>
                </div>
            </div>
        """
        
        # Render every structured section through the shared renderer so the PDF stays in
        # lock-step with the CSV export and the on-page UI. This also fixes the crash: section
        # values are structured dicts/lists, never markdown strings, so they must not be passed
        # to a string formatter (the old code called .strip() on a dict -> AttributeError -> 500).
        for section in render_sections(raw_summary):
            html += self._render_section_html(section)

        html += """
            <div class="footer">
                <p>Generated by EarningsNerd - AI-Powered SEC Filing Analysis</p>
                <p>This AI-generated summary is derived from publicly available SEC filings and is
                provided for informational purposes only. It is not investment advice or a
                recommendation to buy, sell, or hold any security, and it may be incomplete or
                contain errors — the authoritative source is always the original SEC filing.
                Use is subject to the EarningsNerd Terms of Service (earningsnerd.io/terms).</p>
            </div>
        </body>
        </html>
        """

        return html

    def _render_section_html(self, section: Section) -> str:
        parts = [f"<h2>{escape(section.title)}</h2>"]
        for block in section.blocks:
            parts.append(self._render_block_html(block))
        return "".join(parts)

    @staticmethod
    def _render_block_html(block: Block) -> str:
        """Render one Block to HTML. Every value is escaped (filing-derived, untrusted text)."""
        if block.kind in ("paragraph", "subheading"):
            if not block.text:
                return ""
            tag = "h3" if block.kind == "subheading" else "p"
            # Preserve intentional line breaks (escape first, then convert newlines).
            text = escape(block.text).replace("\n", "<br />")
            return f"<{tag}>{text}</{tag}>"
        if block.kind == "quote":
            if not block.text:
                return ""
            text = escape(block.text).replace("\n", "<br />")
            speaker = f" — {escape(block.speaker)}" if block.speaker else ""
            return f"<blockquote>“{text}”{speaker}</blockquote>"
        if block.kind == "bullets":
            if not block.items:
                return ""
            lead = f"<p><strong>{escape(block.text)}</strong></p>" if block.text else ""
            items = "".join(f"<li>{escape(item)}</li>" for item in block.items)
            return f"{lead}<ul>{items}</ul>"
        if block.kind == "table":
            if not block.rows:
                return ""
            thead = ""
            if block.headers:
                head_cells = "".join(f"<th>{escape(h)}</th>" for h in block.headers)
                thead = f"<thead><tr>{head_cells}</tr></thead>"
            body = "".join(
                "<tr>" + "".join(f"<td>{escape(cell)}</td>" for cell in row) + "</tr>"
                for row in block.rows
            )
            return f"<table>{thead}<tbody>{body}</tbody></table>"
        return ""

    def generate_csv(self, summary: Summary, filing: Filing) -> str:
        """Generate a CSV export of the full structured summary (all sections)."""
        output = io.StringIO()
        writer = csv.writer(output)

        # Header
        writer.writerow([f"{filing.company.name} - {filing.filing_type} Summary"])
        writer.writerow([f"Filing Date: {filing.filing_date.strftime('%Y-%m-%d') if filing.filing_date else 'N/A'}"])
        writer.writerow([f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"])
        writer.writerow([])

        # Render every structured section through the shared renderer (single source of truth)
        # so the CSV carries the same content as the PDF and the on-page summary, instead of just
        # the financial-highlights table + risks the old code emitted.
        raw_summary = summary.raw_summary or {}
        for section in render_sections(raw_summary):
            self._write_section_csv(writer, section)

        return output.getvalue()

    @staticmethod
    def _write_section_csv(writer, section: Section) -> None:
        writer.writerow([section.title])
        for block in section.blocks:
            if block.kind in ("paragraph", "subheading"):
                if block.text:
                    writer.writerow([block.text])
            elif block.kind == "quote":
                if block.text:
                    # Curly quotes (not straight ") so csv.writer doesn't double-escape into """…""".
                    line = f"“{block.text}”"
                    if block.speaker:
                        line += f" — {block.speaker}"
                    writer.writerow([line])
            elif block.kind == "bullets":
                if block.text:
                    writer.writerow([block.text])
                    for item in block.items:
                        writer.writerow(["", item])
                else:
                    for item in block.items:
                        writer.writerow([item])
            elif block.kind == "table":
                if block.headers:
                    writer.writerow(block.headers)
                for row in block.rows:
                    writer.writerow(row)
        writer.writerow([])

    async def export_pdf(self, summary: Summary, filing: Filing) -> bytes:
        """Export summary as PDF"""
        try:
            from weasyprint import HTML
            html_content = self.generate_pdf_html(summary, filing)
            # WeasyPrint parse + render is CPU-heavy (hundreds of ms) — off the event loop.
            return await asyncio.to_thread(lambda: HTML(string=html_content).write_pdf())
        except ImportError:
            raise Exception("WeasyPrint is not installed. Install it with: pip install weasyprint")
        except Exception as e:
            raise Exception(f"Failed to generate PDF: {str(e)}")

    @staticmethod
    def _narrative_inline_html(text: str) -> str:
        """Escape, then translate the two inline GFM forms the narrative actually emits —
        ``**bold**`` and ``*italic*`` — into tags. Escape-first keeps the everything-escaped
        posture; both regexes are linear (no nesting, no lazy quantifiers) since this scans
        model output."""
        escaped = escape(text)
        escaped = re.sub(r"\*\*([^*\n]+)\*\*", r"<strong>\1</strong>", escaped)
        # Italic needs tight asterisks (no space inside) so a lone "*" or "5*3" stays literal.
        escaped = re.sub(r"(?<!\*)\*(?!\s)([^*\n]+)(?<!\s)\*(?!\*)", r"<em>\1</em>", escaped)
        return escaped

    @classmethod
    def _narrative_to_html(cls, narrative: str) -> str:
        """Dependency-free markdown→HTML for the analysis narrative: ``## ``/``### `` headings,
        ``- ``/``* `` bullet lists, ``**bold**``/``*italic*`` inline, blank-line paragraphs —
        the GFM subset the trends prompt produces. Previously only ``## `` was handled, so bold
        markers and bullets rendered as literal asterisks/dashes in the paid PDF. Everything is
        escaped; ``[n]`` citation markers stay plain text and resolve against the Sources
        appendix."""
        parts: list[str] = []
        for raw_block in (narrative or "").split("\n\n"):
            lines = [line.strip() for line in raw_block.split("\n")]
            i = 0
            while i < len(lines):
                line = lines[i]
                if not line:
                    i += 1
                elif line.startswith("## "):
                    parts.append(f"<h2>{cls._narrative_inline_html(line[3:].strip())}</h2>")
                    i += 1
                elif line.startswith("### "):
                    parts.append(f"<h3>{cls._narrative_inline_html(line[4:].strip())}</h3>")
                    i += 1
                elif line.startswith(("- ", "* ")):
                    items = []
                    while i < len(lines) and lines[i].startswith(("- ", "* ")):
                        items.append(f"<li>{cls._narrative_inline_html(lines[i][2:].strip())}</li>")
                        i += 1
                    parts.append("<ul>" + "".join(items) + "</ul>")
                else:
                    para = [line]
                    while (
                        i + 1 < len(lines)
                        and lines[i + 1]
                        and not lines[i + 1].startswith(("## ", "### ", "- ", "* "))
                    ):
                        i += 1
                        para.append(lines[i])
                    parts.append(f"<p>{cls._narrative_inline_html(' '.join(para))}</p>")
                    i += 1
        return "\n".join(parts)

    def generate_analysis_pdf_html(self, analysis, company) -> str:
        """HTML for a Multi-Period Analysis export: header, narrative, metrics-by-period grid, and
        the verified-citations appendix. Charts render as the grid (WeasyPrint runs no JS).

        ``analysis`` is a TrendAnalysis row (dataset_json + narrative_md + citations_json),
        ``company`` its Company. A dedicated template rather than the summary_sections renderer —
        an analysis is grid + narrative shaped, not filing-section shaped.
        """
        dataset = analysis.dataset_json or {}
        periods = [p.get("key", "") for p in dataset.get("periods", [])]
        mode_label = "Annual" if analysis.mode == "annual" else "Quarterly"

        def format_value(value, unit, percent) -> str:
            if value is None:
                return "—"
            if percent:
                return f"{value:.1f}%"
            if unit == "pure":
                return f"{value:.2f}x"
            if isinstance(unit, str) and unit.endswith("/shares"):
                return f"{value:,.2f}"
            return f"{value:,.0f}"

        header_cells = "".join(f"<th>{escape(period)}</th>" for period in periods)
        body_rows = []
        for series in dataset.get("series", []):
            by_period = {p.get("period"): p for p in series.get("points", [])}
            cells = []
            for period in periods:
                point = by_period.get(period) or {}
                rendered = format_value(
                    point.get("value"), series.get("unit", "USD"), bool(series.get("percent"))
                )
                if point.get("derived"):
                    rendered += " †"
                cells.append(f'<td class="num">{escape(rendered)}</td>')
            body_rows.append(
                f"<tr><td>{escape(series.get('label', series.get('concept', '')))}</td>"
                + "".join(cells)
                + "</tr>"
            )

        citation_items = "".join(
            f"<li><strong>[{c.get('n')}]</strong> {escape(str(c.get('excerpt', '')))}"
            f" <span class=\"ref\">{escape(str(c.get('section_ref') or ''))}</span></li>"
            for c in (analysis.citations_json or [])
        )
        has_derived = any(
            p.get("derived")
            for series in dataset.get("series", [])
            for p in series.get("points", [])
        )
        derived_note = (
            '<p class="footnote">† Computed fourth quarter: full year minus the three reported quarters.</p>'
            if has_derived
            else ""
        )
        # "Generated" = when the AI actually wrote this narrative (the row's timestamps) — a
        # cached analysis exported weeks later must not present itself as freshly generated.
        generated_at = getattr(analysis, "updated_at", None) or getattr(analysis, "created_at", None)
        generated_date = (generated_at or datetime.now()).strftime("%B %d, %Y")
        exported_date = datetime.now().strftime("%B %d, %Y")

        return f"""
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="UTF-8">
            <style>
                body {{
                    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
                    line-height: 1.6; color: #1f2937; max-width: 800px; margin: 0 auto; padding: 40px 20px;
                }}
                h1 {{ color: #111827; border-bottom: 3px solid #4F7A63; padding-bottom: 10px; margin-bottom: 6px; }}
                h2 {{ color: #1f2937; margin-top: 26px; margin-bottom: 10px; border-bottom: 1px solid #e5e7eb; padding-bottom: 5px; }}
                .meta {{ color: #6b7280; font-size: 13px; margin-bottom: 24px; }}
                table {{ width: 100%; border-collapse: collapse; margin: 20px 0; font-size: 11px; }}
                th, td {{ border: 1px solid #e5e7eb; padding: 6px 8px; text-align: left; }}
                th {{ background-color: #f3f4f6; font-weight: 600; }}
                td.num {{ text-align: right; font-variant-numeric: tabular-nums; }}
                ol.sources {{ font-size: 11px; color: #374151; padding-left: 18px; }}
                .ref {{ color: #6b7280; }}
                .footnote {{ color: #6b7280; font-size: 11px; margin-top: 18px; }}
            </style>
        </head>
        <body>
            <h1>{escape(company.name)} — Multi-Period Analysis</h1>
            <div class="meta">
                {escape(company.ticker or "")} · {mode_label} · {escape(analysis.period_key)} ·
                Generated {generated_date} · Exported {exported_date} · EarningsNerd
            </div>

            {self._narrative_to_html(analysis.narrative_md or "")}

            <h2>Metrics by period</h2>
            <table>
                <tr><th>Metric</th>{header_cells}</tr>
                {"".join(body_rows)}
            </table>
            {derived_note}

            <h2>Sources</h2>
            <ol class="sources">{citation_items}</ol>
            <p class="footnote">
                All figures from SEC XBRL (companyfacts). Growth rates, margins and ratios are
                computed by EarningsNerd; the AI narrative cites only values from this dataset.
            </p>
            <h2>About this document</h2>
            <p class="footnote">
                This analysis was generated by EarningsNerd (earningsnerd.io) using automated AI
                models on {generated_date} and exported on {exported_date}. Data reflects SEC
                filings available at generation time. All underlying figures come from the company's XBRL
                filings with the U.S. Securities and Exchange Commission (SEC EDGAR,
                companyfacts); growth rates, margins, ratios, and any values marked † are
                computed by EarningsNerd and do not appear in the filings themselves.
                AI-generated text may be incomplete, out of date, or wrong; the authoritative
                source is always the original SEC filing.
            </p>
            <p class="footnote">
                This document is provided for general informational and research purposes only.
                It is not investment, financial, legal, accounting, or tax advice; it is not a
                recommendation or solicitation to buy, sell, or hold any security; and
                EarningsNerd is not a broker-dealer, investment adviser, or fiduciary. Past
                performance is not indicative of future results. Use is subject to the
                EarningsNerd Terms of Service (earningsnerd.io/terms), including its disclaimer
                of warranties and limitation of liability. EarningsNerd is not affiliated with
                or endorsed by the SEC.
            </p>
        </body>
        </html>
        """

    async def export_analysis_pdf(self, analysis, company) -> bytes:
        """Export a Multi-Period Analysis as PDF (same WeasyPrint path as export_pdf)."""
        try:
            from weasyprint import HTML
            html_content = self.generate_analysis_pdf_html(analysis, company)
            # WeasyPrint parse + render is CPU-heavy (hundreds of ms) — off the event loop.
            return await asyncio.to_thread(lambda: HTML(string=html_content).write_pdf())
        except ImportError:
            raise Exception("WeasyPrint is not installed. Install it with: pip install weasyprint")
        except Exception as e:
            raise Exception(f"Failed to generate PDF: {str(e)}")

export_service = ExportService()

