from datetime import datetime
from html import escape
from app.models import Summary, Filing
from app.services.summary_sections import Block, Section, render_sections
import io
import csv

class ExportService:
    def __init__(self):
        pass

    def generate_pdf_html(self, summary: Summary, filing: Filing) -> str:
        """Generate HTML for PDF export"""
        raw_summary = summary.raw_summary or {}

        html = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="UTF-8">
            <style>
                body {{
                    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
                    line-height: 1.6;
                    color: #1f2937;
                    max-width: 800px;
                    margin: 0 auto;
                    padding: 40px 20px;
                }}
                h1 {{
                    color: #111827;
                    border-bottom: 3px solid #3b82f6;
                    padding-bottom: 10px;
                    margin-bottom: 30px;
                }}
                h2 {{
                    color: #1f2937;
                    margin-top: 30px;
                    margin-bottom: 15px;
                    border-bottom: 1px solid #e5e7eb;
                    padding-bottom: 5px;
                }}
                h3 {{
                    color: #374151;
                    margin-top: 20px;
                    margin-bottom: 10px;
                }}
                table {{
                    width: 100%;
                    border-collapse: collapse;
                    margin: 20px 0;
                }}
                th, td {{
                    border: 1px solid #e5e7eb;
                    padding: 12px;
                    text-align: left;
                }}
                th {{
                    background-color: #f3f4f6;
                    font-weight: 600;
                }}
                .header {{
                    margin-bottom: 30px;
                    padding-bottom: 20px;
                    border-bottom: 2px solid #e5e7eb;
                }}
                .metadata {{
                    color: #6b7280;
                    font-size: 0.9em;
                    margin-bottom: 10px;
                }}
                .footer {{
                    margin-top: 40px;
                    padding-top: 20px;
                    border-top: 1px solid #e5e7eb;
                    color: #6b7280;
                    font-size: 0.85em;
                    text-align: center;
                }}
                ul {{
                    margin: 10px 0;
                    padding-left: 20px;
                }}
                li {{
                    margin: 5px 0;
                }}
                blockquote {{
                    margin: 10px 0;
                    padding-left: 15px;
                    border-left: 3px solid #e5e7eb;
                    color: #374151;
                    font-style: italic;
                }}
            </style>
        </head>
        <body>
            <div class="header">
                <h1>{escape(filing.company.name or '')} - {escape(filing.filing_type or '')} Summary</h1>
                <div class="metadata">
                    <p><strong>Filing Date:</strong> {filing.filing_date.strftime('%B %d, %Y') if filing.filing_date else 'N/A'}</p>
                    <p><strong>Period End:</strong> {filing.period_end_date.strftime('%B %d, %Y') if filing.period_end_date else 'N/A'}</p>
                    <p><strong>Generated:</strong> {datetime.now().strftime('%B %d, %Y at %I:%M %p')}</p>
                    <p><strong>Source:</strong> SEC EDGAR - {escape(filing.sec_url or '')}</p>
                </div>
            </div>
        """
        
        # Render every structured section through the shared renderer so the PDF stays in
        # lock-step with the CSV export and the on-page UI. This also fixes the crash: section
        # values are structured dicts/lists, never markdown strings, so they must not be passed
        # to a string formatter (the old code called .strip() on a dict -> AttributeError -> 500).
        for section in render_sections(raw_summary):
            html += self._render_section_html(section)

        html += """
            <div class="footer">
                <p>Generated by EarningsNerd - AI-Powered SEC Filing Analysis</p>
                <p>This summary is derived from publicly available SEC filings and is for informational purposes only.</p>
            </div>
        </body>
        </html>
        """

        return html

    def _render_section_html(self, section: Section) -> str:
        parts = [f"<h2>{escape(section.title)}</h2>"]
        for block in section.blocks:
            parts.append(self._render_block_html(block))
        return "".join(parts)

    @staticmethod
    def _render_block_html(block: Block) -> str:
        """Render one Block to HTML. Every value is escaped (filing-derived, untrusted text)."""
        if block.kind in ("paragraph", "subheading"):
            if not block.text:
                return ""
            tag = "h3" if block.kind == "subheading" else "p"
            # Preserve intentional line breaks (escape first, then convert newlines).
            text = escape(block.text).replace("\n", "<br />")
            return f"<{tag}>{text}</{tag}>"
        if block.kind == "quote":
            if not block.text:
                return ""
            text = escape(block.text).replace("\n", "<br />")
            speaker = f" — {escape(block.speaker)}" if block.speaker else ""
            return f"<blockquote>“{text}”{speaker}</blockquote>"
        if block.kind == "bullets":
            if not block.items:
                return ""
            lead = f"<p><strong>{escape(block.text)}</strong></p>" if block.text else ""
            items = "".join(f"<li>{escape(item)}</li>" for item in block.items)
            return f"{lead}<ul>{items}</ul>"
        if block.kind == "table":
            if not block.rows:
                return ""
            thead = ""
            if block.headers:
                head_cells = "".join(f"<th>{escape(h)}</th>" for h in block.headers)
                thead = f"<thead><tr>{head_cells}</tr></thead>"
            body = "".join(
                "<tr>" + "".join(f"<td>{escape(cell)}</td>" for cell in row) + "</tr>"
                for row in block.rows
            )
            return f"<table>{thead}<tbody>{body}</tbody></table>"
        return ""

    def generate_csv(self, summary: Summary, filing: Filing) -> str:
        """Generate a CSV export of the full structured summary (all sections)."""
        output = io.StringIO()
        writer = csv.writer(output)

        # Header
        writer.writerow([f"{filing.company.name} - {filing.filing_type} Summary"])
        writer.writerow([f"Filing Date: {filing.filing_date.strftime('%Y-%m-%d') if filing.filing_date else 'N/A'}"])
        writer.writerow([f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"])
        writer.writerow([])

        # Render every structured section through the shared renderer (single source of truth)
        # so the CSV carries the same content as the PDF and the on-page summary, instead of just
        # the financial-highlights table + risks the old code emitted.
        raw_summary = summary.raw_summary or {}
        for section in render_sections(raw_summary):
            self._write_section_csv(writer, section)

        return output.getvalue()

    @staticmethod
    def _write_section_csv(writer, section: Section) -> None:
        writer.writerow([section.title])
        for block in section.blocks:
            if block.kind in ("paragraph", "subheading"):
                if block.text:
                    writer.writerow([block.text])
            elif block.kind == "quote":
                if block.text:
                    # Curly quotes (not straight ") so csv.writer doesn't double-escape into """…""".
                    line = f"“{block.text}”"
                    if block.speaker:
                        line += f" — {block.speaker}"
                    writer.writerow([line])
            elif block.kind == "bullets":
                if block.text:
                    writer.writerow([block.text])
                    for item in block.items:
                        writer.writerow(["", item])
                else:
                    for item in block.items:
                        writer.writerow([item])
            elif block.kind == "table":
                if block.headers:
                    writer.writerow(block.headers)
                for row in block.rows:
                    writer.writerow(row)
        writer.writerow([])

    async def export_pdf(self, summary: Summary, filing: Filing) -> bytes:
        """Export summary as PDF"""
        try:
            from weasyprint import HTML
            html_content = self.generate_pdf_html(summary, filing)
            html = HTML(string=html_content)
            pdf_bytes = html.write_pdf()
            return pdf_bytes
        except ImportError:
            raise Exception("WeasyPrint is not installed. Install it with: pip install weasyprint")
        except Exception as e:
            raise Exception(f"Failed to generate PDF: {str(e)}")

export_service = ExportService()

