"""Index-membership universe for the earnings calendar (S&P 500 ∪ Nasdaq 100).

The served universe is the committed ``backend/app/data/index_membership.json``, regenerated by
``scripts/refresh_index_membership.py`` and reviewed in a PR — it is NEVER fetched at runtime, so a
bad/empty provider response can't corrupt or empty the calendar. The file is loaded once at import
into a frozenset.

The single gate every calendar call site uses is ``active_member_filter()``: it returns the member
set only when the feature flag is on AND the loaded list is sane (>= ``SANITY_FLOOR``). Otherwise it
returns ``None`` and callers serve UNFILTERED. A missing/corrupt/short list must degrade to
"show everything," never to an empty calendar — the filter can only ever *hide* tail names, so the
fail-open direction is the safe one.
"""
from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Optional

from app.config import settings

logger = logging.getLogger(__name__)

_DATA_PATH = Path(__file__).resolve().parents[1] / "data" / "index_membership.json"

# S&P 500 alone is ~503 tickers; below this the list is presumed broken and the filter disables
# itself (serves unfiltered) rather than hide most of the market. Mirrors the regen script's floor.
SANITY_FLOOR = 450


def normalize_ticker(raw: str) -> str:
    """Canonical comparison form for a ticker.

    Alpha Vantage (the calendar's ticker source) writes dual classes with a DOT — ``BRK.B``,
    ``BF.B`` — while some sources (FMP) use a DASH (``BRK-B``). Canonicalizing ``-`` -> ``.`` plus
    upper/strip makes the committed list match AV's stored event tickers regardless of which source
    generated it.
    """
    return (raw or "").strip().upper().replace("-", ".")


def _load() -> frozenset[str]:
    try:
        payload = json.loads(_DATA_PATH.read_text(encoding="utf-8"))
        tickers = {
            normalize_ticker(m["ticker"])
            for m in payload.get("members", [])
            if isinstance(m, dict) and m.get("ticker")
        }
        tickers.discard("")
        if len(tickers) < SANITY_FLOOR:
            logger.error(
                "index_membership.json has %d < %d tickers; calendar index filter will stay OFF "
                "(serving unfiltered) until the list is repaired.",
                len(tickers), SANITY_FLOOR,
            )
            return frozenset()
        return frozenset(tickers)
    except Exception:
        logger.exception(
            "Failed to load index_membership.json; calendar index filter disabled (unfiltered)."
        )
        return frozenset()


_MEMBER_TICKERS: frozenset[str] = _load()


def member_tickers() -> frozenset[str]:
    """The full normalized member set (may be empty if the list failed to load)."""
    return _MEMBER_TICKERS


def is_member(ticker: str) -> bool:
    return normalize_ticker(ticker) in _MEMBER_TICKERS


def active_member_filter() -> Optional[frozenset[str]]:
    """The member set to filter calendar queries by, or ``None`` when no filter must apply.

    ``None`` ("serve unfiltered") is returned when the feature flag is off OR the loaded list failed
    the sanity floor. Callers apply a ticker filter only when this is non-None — that is what
    guarantees a missing/short list can never empty the calendar.
    """
    if not settings.CALENDAR_INDEX_FILTER_ENABLED:
        return None
    if not _MEMBER_TICKERS:  # load failed / below floor -> fail open (show everything)
        return None
    return _MEMBER_TICKERS


# Public identifiers for the universe the calendar is currently serving. Surfaced on the
# /api/calendar response so the UI can label its coverage accurately in EVERY flag state — the
# "S&P 500 & Nasdaq 100" caption shows only when the filter is genuinely active, never during a
# pre-flip window or a rollback.
UNIVERSE_INDEX = "sp500_nasdaq100"
UNIVERSE_ALL = "all"


def active_universe_label() -> str:
    """``"sp500_nasdaq100"`` when the index filter is active, else ``"all"`` (serving unfiltered)."""
    return UNIVERSE_INDEX if active_member_filter() is not None else UNIVERSE_ALL
