import { Metadata } from 'next'
import Link from 'next/link'
import { LEGAL_DATES } from '@/lib/legalDates'

export const metadata: Metadata = {
  title: 'Terms of Service | EarningsNerd',
  description:
    'Terms of Service for EarningsNerd — the rules for using our AI-powered SEC filing analysis.',
}

export default function TermsPage() {
  // Content-change date — lives in lib/legalDates.ts with the full rationale.
  const lastUpdated = LEGAL_DATES.terms

  return (
    <main className="mx-auto max-w-4xl px-4 py-12 sm:px-6 lg:px-8">
      <div className="max-w-none">
        <h1 className="text-4xl font-semibold text-text-primary-light dark:text-text-primary-dark">
          Terms of Service
        </h1>
        <p className="text-lg text-text-secondary-light dark:text-text-secondary-dark">
          Last updated: {lastUpdated}
        </p>

        <section className="mt-8">
          <h2 className="text-2xl font-semibold text-text-primary-light dark:text-text-primary-dark">
            1. Agreement to these Terms
          </h2>
          <p className="text-text-secondary-light dark:text-text-secondary-dark">
            These Terms of Service (&quot;Terms&quot;) govern your access to and use of EarningsNerd
            (the &quot;Service&quot;). By creating an account, joining the waitlist, or otherwise using the
            Service, you agree to be bound by these Terms and by our{' '}
            <Link href="/privacy" className="text-brand-strong hover:underline dark:text-brand-strong-dark">
              Privacy Policy
            </Link>
            . If you do not agree, do not use the Service.
          </p>
        </section>

        <section className="mt-8">
          <h2 className="text-2xl font-semibold text-text-primary-light dark:text-text-primary-dark">
            2. What EarningsNerd is
          </h2>
          <p className="text-text-secondary-light dark:text-text-secondary-dark">
            EarningsNerd uses generative AI to summarize and analyze public filings from the U.S.
            Securities and Exchange Commission&apos;s EDGAR system (such as 10-K and 10-Q reports) and
            related market data. The Service is an informational and research tool only.
          </p>
        </section>

        <section className="mt-8">
          <h2 className="text-2xl font-semibold text-text-primary-light dark:text-text-primary-dark">
            3. Not investment, financial, legal, or tax advice
          </h2>
          <p className="text-text-secondary-light dark:text-text-secondary-dark">
            <strong>
              EarningsNerd does not provide investment, financial, legal, accounting, or tax advice.
            </strong>{' '}
            Nothing on the Service is a recommendation to buy, sell, or hold any security or to make
            any financial decision, and we are not a broker-dealer, investment adviser, or fiduciary.
            Summaries and analyses are provided for general informational purposes only and may not be
            suitable for your circumstances. You are solely responsible for your own investment
            decisions and should consult a licensed professional and review the underlying filings
            before acting. Past performance is not indicative of future results.
          </p>
        </section>

        <section className="mt-8">
          <h2 className="text-2xl font-semibold text-text-primary-light dark:text-text-primary-dark">
            4. AI-generated content and accuracy
          </h2>
          <p className="text-text-secondary-light dark:text-text-secondary-dark">
            Summaries are generated by automated AI models and may be incomplete, out of date, or
            contain errors (including misstated figures). Always verify any information against the
            original filing on{' '}
            <a
              href="https://www.sec.gov/edgar"
              target="_blank"
              rel="noreferrer"
              className="text-brand-strong hover:underline dark:text-brand-strong-dark"
            >
              SEC EDGAR
            </a>{' '}
            before relying on it. The authoritative source is always the original SEC filing, not our
            summary of it.
          </p>
        </section>

        <section className="mt-8">
          <h2 className="text-2xl font-semibold text-text-primary-light dark:text-text-primary-dark">
            5. Accounts
          </h2>
          <ul className="list-disc space-y-2 pl-6 text-text-secondary-light dark:text-text-secondary-dark">
            <li>You must provide accurate information and keep your account credentials secure.</li>
            <li>You are responsible for all activity that occurs under your account.</li>
            <li>You must be at least the age of majority in your jurisdiction to use the Service.</li>
            <li>Notify us promptly of any unauthorized use of your account.</li>
          </ul>
        </section>

        <section className="mt-8">
          <h2 className="text-2xl font-semibold text-text-primary-light dark:text-text-primary-dark">
            6. Acceptable use
          </h2>
          <p className="text-text-secondary-light dark:text-text-secondary-dark">You agree not to:</p>
          <ul className="list-disc space-y-2 pl-6 text-text-secondary-light dark:text-text-secondary-dark">
            <li>
              Scrape, bulk-download, resell, or redistribute the Service&apos;s output except as
              expressly permitted.
            </li>
            <li>
              Probe, attack, or attempt to disrupt the Service, circumvent rate limits or access
              controls, or use automated means to create accounts.
            </li>
            <li>Reverse engineer the Service except to the extent permitted by applicable law.</li>
            <li>Use the Service to violate any law or third-party right, or to mislead others.</li>
          </ul>
        </section>

        <section className="mt-8">
          <h2 className="text-2xl font-semibold text-text-primary-light dark:text-text-primary-dark">
            7. Subscriptions, billing, and free tiers
          </h2>
          <p className="text-text-secondary-light dark:text-text-secondary-dark">
            Some features may be offered free of charge, subject to usage limits, and others may
            require a paid subscription. Paid plans are billed through our payment processor (Stripe);
            we do not store your full card details. Subscriptions renew automatically until cancelled,
            and you may cancel at any time effective at the end of the current billing period. Except
            where required by law, fees are non-refundable. We may change pricing or plan features on
            reasonable notice.
          </p>
        </section>

        <section className="mt-8">
          <h2 className="text-2xl font-semibold text-text-primary-light dark:text-text-primary-dark">
            8. Intellectual property and third-party data
          </h2>
          <p className="text-text-secondary-light dark:text-text-secondary-dark">
            The Service, including its software, design, and original content, is owned by EarningsNerd
            and protected by intellectual-property laws. SEC filing data is sourced from public
            government records (SEC EDGAR); certain market data may be provided by third parties under
            their own terms. We grant you a limited, non-exclusive, non-transferable right to use the
            Service for your own internal, non-commercial research, subject to these Terms.
          </p>
        </section>

        <section className="mt-8">
          <h2 className="text-2xl font-semibold text-text-primary-light dark:text-text-primary-dark">
            9. Disclaimer of warranties
          </h2>
          <p className="text-text-secondary-light dark:text-text-secondary-dark">
            THE SERVICE IS PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; WITHOUT WARRANTIES OF
            ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR
            A PARTICULAR PURPOSE, ACCURACY, AND NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SERVICE
            WILL BE UNINTERRUPTED, ERROR-FREE, OR THAT ANY SUMMARY OR DATA IS ACCURATE OR COMPLETE.
          </p>
        </section>

        <section className="mt-8">
          <h2 className="text-2xl font-semibold text-text-primary-light dark:text-text-primary-dark">
            10. Limitation of liability
          </h2>
          <p className="text-text-secondary-light dark:text-text-secondary-dark">
            TO THE MAXIMUM EXTENT PERMITTED BY LAW, EARNINGSNERD AND ITS OFFICERS, EMPLOYEES, AND
            SUPPLIERS WILL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR
            PUNITIVE DAMAGES, OR FOR ANY INVESTMENT OR TRADING LOSSES, ARISING OUT OF OR RELATED TO
            YOUR USE OF THE SERVICE. OUR TOTAL LIABILITY FOR ANY CLAIM WILL NOT EXCEED THE GREATER OF
            (A) THE AMOUNTS YOU PAID US IN THE 12 MONTHS BEFORE THE CLAIM OR (B) USD $100.
          </p>
        </section>

        <section className="mt-8">
          <h2 className="text-2xl font-semibold text-text-primary-light dark:text-text-primary-dark">
            11. Indemnification
          </h2>
          <p className="text-text-secondary-light dark:text-text-secondary-dark">
            You agree to indemnify and hold EarningsNerd harmless from any claims, losses, and expenses
            (including reasonable legal fees) arising from your misuse of the Service or violation of
            these Terms.
          </p>
        </section>

        <section className="mt-8">
          <h2 className="text-2xl font-semibold text-text-primary-light dark:text-text-primary-dark">
            12. Termination
          </h2>
          <p className="text-text-secondary-light dark:text-text-secondary-dark">
            You may stop using the Service and delete your account at any time from your{' '}
            <Link
              href="/dashboard/settings"
              className="text-brand-strong hover:underline dark:text-brand-strong-dark"
            >
              account settings
            </Link>
            . We may suspend or terminate access if you breach these Terms or to protect the Service.
          </p>
        </section>

        <section className="mt-8">
          <h2 className="text-2xl font-semibold text-text-primary-light dark:text-text-primary-dark">
            13. Changes to these Terms
          </h2>
          <p className="text-text-secondary-light dark:text-text-secondary-dark">
            We may update these Terms from time to time. When we do, we will revise the
            &quot;Last updated&quot; date above and, where appropriate, provide additional notice.
            Continued use of the Service after changes take effect constitutes acceptance.
          </p>
        </section>

        <section className="mt-8">
          <h2 className="text-2xl font-semibold text-text-primary-light dark:text-text-primary-dark">
            14. Governing law
          </h2>
          <p className="text-text-secondary-light dark:text-text-secondary-dark">
            These Terms are governed by the laws applicable where EarningsNerd is established, without
            regard to conflict-of-laws principles, and the courts located there will have jurisdiction,
            except where mandatory consumer-protection law provides otherwise.
          </p>
        </section>

        <section className="mt-8">
          <h2 className="text-2xl font-semibold text-text-primary-light dark:text-text-primary-dark">
            15. Contact
          </h2>
          <p className="text-text-secondary-light dark:text-text-secondary-dark">
            Questions about these Terms? Reach us through our{' '}
            <Link href="/contact" className="text-brand-strong hover:underline dark:text-brand-strong-dark">
              contact page
            </Link>
            .
          </p>
        </section>
      </div>
    </main>
  )
}
