'use client'

// Single client boundary for Phosphor icons. @phosphor-icons/react creates a React
// context at import time (illegal in Server Components); re-exporting through this
// 'use client' module keeps that context in the client graph, so Server Components can
// still render icons. Import icons from '@/lib/icons' app-wide (not the package directly).
export {
  ArrowClockwiseIcon,
  ArrowDownRightIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowSquareOutIcon,
  ArrowUpRightIcon,
  ArrowsClockwiseIcon,
  ArrowsCounterClockwiseIcon,
  BellIcon,
  BookmarkSimpleIcon,
  BrainIcon,
  BuildingOfficeIcon,
  CalendarBlankIcon,
  CalendarDotsIcon,
  CaretDownIcon,
  CaretLeftIcon,
  ChartBarIcon,
  CheckCircleIcon,
  CheckIcon,
  CircleNotchIcon,
  ClockIcon,
  ColumnsIcon,
  CookieIcon,
  CopyIcon,
  CreditCardIcon,
  DatabaseIcon,
  DownloadSimpleIcon,
  EnvelopeSimpleIcon,
  EnvelopeSimpleOpenIcon,
  EyeIcon,
  EyeSlashIcon,
  FileArrowDownIcon,
  FileTextIcon,
  FlameIcon,
  FunnelIcon,
  GearIcon,
  GitDiffIcon,
  HouseIcon,
  InfoIcon,
  KeyIcon,
  LightningIcon,
  LinkIcon,
  ListIcon,
  LockSimpleIcon,
  MagnifyingGlassIcon,
  MinusIcon,
  MoonIcon,
  NewspaperIcon,
  PaperPlaneTiltIcon,
  PlusIcon,
  ProhibitIcon,
  PulseIcon,
  QuestionIcon,
  SealCheckIcon,
  ShieldCheckIcon,
  ShieldIcon,
  ShieldWarningIcon,
  SignOutIcon,
  SparkleIcon,
  SquaresFourIcon,
  StarIcon,
  SunIcon,
  TrashIcon,
  TrendDownIcon,
  TrendUpIcon,
  UserIcon,
  WarningCircleIcon,
  WarningIcon,
  XCircleIcon,
  XIcon,
} from '@phosphor-icons/react'
